POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json

{
    "content" : "This is a new note",
    "important": true,
    "userId": "614e558d48556340b81309fa"
}

###

POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json

{
    "content" : "This is new note without importance"
}


###

POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json

{
    #This not work. 
}