POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjE0ZTU1OGQ0ODU1NjM0MGI4MTMwOWZhIiwidXNlcm5hbWUiOiJqdWFucjEwIn0sImlhdCI6MTYzNTYzOTQzNCwiZXhwIjoxNjM1NjQzMDM0fQ.f5IaLBUmMMCUFeWRWOn12KjOs05gY9GU6Fr2CBPp9Tw

{
    "content" : "This is a new note with token",
    "important": true
}

###

POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json

{
    "content" : "This is new note without importance"
}


###

POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjE0ZTU1OGQ0ODU1NjM0MGI4MTMwOWZhIiwidXNlcm5hbWUiOiJqdWFucjEwIn0sImlhdCI6MTYzNTYyMDkwMywiZXhwIjoxNjM1NjI0NTAzfQ.xTatrV023qcNaNcwkAmRjuoidcHWJrWhPdAFuAaFU1Q

{
    #This not work. 
}